// Builds Snake3D/levels.js from the world scripts in tools/worlds and checks them.
//   node tools/build-levels.js          check every world and write levels.js
//   node tools/build-levels.js --check  check only
// The worlds appear in the menu after the two original maps, in the order of WORLDS.
const fs = require('fs');
const path = require('path');
const {hexStep, MOVES} = require('./grid');

const WORLDS = ['weave', 'spiral', 'hive', 'garden', 'blocks', 'candy'];

function check(world) {
  const {grid: g, start} = world;
  const errors = [];
  const at = (side, c, r) => g.get(side, ((c % g.w) + g.w) % g.w, ((r % g.h) + g.h) % g.h);
  // Holes go through the whole slab, so both faces must agree on them.
  for (let r = 0; r < g.h; r++) for (let c = 0; c < g.w; c++)
    if ((g.top[r][c] === ' ') !== (g.bottom[r][c] === ' ')) errors.push(`hole at ${c},${r} on one face only`);
  const [sc, sr] = start;
  if (!/[.a-zA-Z]/.test(g.top[sr][sc])) errors.push(`start ${sc},${sr} is not plain floor`);
  // Letters: where they are and whether a stage uses them.
  const cells = new Map();
  for (const side of ['top', 'bottom']) for (let r = 0; r < g.h; r++) for (let c = 0; c < g.w; c++) {
    const ch = g[side][r][c];
    if (!/[a-zA-Z]/.test(ch)) continue;
    if (!cells.has(ch)) cells.set(ch, {side, list: []});
    const e = cells.get(ch);
    if (e.side !== side) errors.push(`letter ${ch} is on both faces`);
    e.list.push([c, r]);
  }
  const used = new Set(g.stages.join(''));
  for (const ch of cells.keys()) if (!used.has(ch)) errors.push(`letter ${ch} is not in any stage`);
  const neighbours = (c, r) => g.hex
    ? ['N', 'NE', 'SE', 'S', 'SW', 'NW'].map(m => hexStep(c, r, m, g.h))
    : Object.values(MOVES).map(([dc, dr]) => [c + dc, r + dr]);
  const wrap = ([c, r]) => `${((c % g.w) + g.w) % g.w},${((r % g.h) + g.h) % g.h}`;
  g.stages.forEach((stage, i) => {
    if (!stage) errors.push(`stage ${i + 1} is empty`);
    for (const ch of stage) {
      const e = cells.get(ch);
      if (!e) { errors.push(`stage ${i + 1}: letter ${ch} is not on the map`); continue; }
      for (const [c, r] of e.list) if (e.side === 'bottom' && !/[.a-zA-Z]/.test(at('top', c, r))) errors.push(`stage ${i + 1}: ${ch} at ${c},${r} lies under a top tile`);
      if (ch < 'a') continue;   // every cell of an upper-case letter is a crystal of its own
      // A chain must be one path: every cell has two chain neighbours except the two ends.
      const set = new Set(e.list.map(wrap));
      const degree = e.list.map(([c, r]) => new Set(neighbours(c, r).map(wrap).filter(k => set.has(k))).size);
      const ends = degree.filter(d => d === 1).length;
      if (e.list.length > 1 && (ends !== 2 || degree.some(d => d > 2 || d === 0))) errors.push(`stage ${i + 1}: chain ${ch} is not a single path`);
    }
  });
  return errors;
}

function source(world) {
  const q = s => `'${s}'`;
  const layer = l => `[${l.map(v => Array.isArray(v) ? `[${v.join(', ')}]` : q(v)).join(', ')}]`;
  const rows = side => world.grid.ascii(side).map(r => '      ' + q(r)).join(',\n');
  return `  {
    key: ${q(world.key)}, name: ${q(world.name)}, kind: ${q(world.kind)}, hex: ${world.grid.hex},
    start: [${world.start[0]}, ${world.start[1]}, ${q(world.start[2])}],
    stages: [${world.grid.stages.map(q).join(', ')}],
    colors: {
      top: [${world.colors.top.map(layer).join(', ')}],
      bottom: [${world.colors.bottom.map(layer).join(', ')}]
    },
    top: [
${rows('top')}
    ],
    bottom: [
${rows('bottom')}
    ]
  }`;
}

const worlds = WORLDS.map(name => require(`./worlds/${name}`));
let failed = false;
for (const w of worlds) {
  const errors = check(w);
  console.log(`${w.key}: ${w.grid.w}x${w.grid.h}${w.grid.hex ? ' hex' : ''}, ${w.grid.stages.length} stages${errors.length ? '' : ', ok'}`);
  for (const e of errors) console.log('  ' + e);
  if (errors.length) failed = true;
}
if (failed) process.exit(1);
if (!process.argv.includes('--check')) {
  const header = `/* Snakes 3D: new worlds. Generated by tools/build-levels.js from tools/worlds/*.js; edit those and rebuild.
   Each face is drawn as text, one character per cell, the first line being the north edge; a world is as
   wide as its longest line and wraps round at its edges.
   ' ' hole (the snake wraps round its edge to the other face), '.' floor, '#' wall, '^' spike,
   '>' boost pad, '=' slow pad. Letters are items on that face: every cell of an upper-case letter is a
   crystal, all cells of one lower-case letter form a chain that has to be taken in one run.
   stages: the letters of every stage in play order. start: [column, line, heading] on top.
   colors: gradient layers per face, [from, to, x | y | d(iagonal) | r(adial), optional [c0, l0, c1, l1]]. */
window.SNAKES_LEVELS = [
`;
  fs.writeFileSync(path.join(__dirname, '..', 'levels.js'), header + worlds.map(source).join(',\n') + '\n];\n');
  console.log('wrote levels.js');
}
